import { CodingExercise } from '../../../../core/types';

export const topic2Exercises: CodingExercise[] = [
  {
    id: 'math304-t2-ex01',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Check if Element Generates Group',
    difficulty: 1,
    description: 'Determine if a given element generates the entire group. An element g generates a group if every element can be expressed as g^n for some integer n.',
    starterCode: `def is_generator(element, elements, operation_table, identity):
    """
    Check if element generates the entire group.

    Args:
        element: The potential generator
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if element generates the group, False otherwise
    """
    pass`,
    solution: `def is_generator(element, elements, operation_table, identity):
    """
    Check if element generates the entire group.

    Args:
        element: The potential generator
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if element generates the group, False otherwise
    """
    generated = set()
    current = identity
    n = len(elements)

    for _ in range(n):
        generated.add(current)
        element_index = elements.index(element)
        current_index = elements.index(current)
        current = operation_table[current_index][element_index]

    return generated == set(elements)`,
    testCases: [
      { input: '1, [0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: 'True', isHidden: false, description: '1 generates Z5' },
      { input: '2, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: 'True', isHidden: false, description: '2 generates Z4' },
      { input: '2, [0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: 'False', isHidden: true, description: '2 does not generate Z5' }
    ],
    hints: ['Generate all powers of the element', 'Check if the generated set equals the entire group'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex02',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find All Generators',
    difficulty: 2,
    description: 'Find all generators of a cyclic group. A cyclic group has at least one element that generates the entire group.',
    starterCode: `def find_all_generators(elements, operation_table, identity):
    """
    Find all generators of the group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of all generators
    """
    pass`,
    solution: `def find_all_generators(elements, operation_table, identity):
    """
    Find all generators of the group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of all generators
    """
    generators = []
    n = len(elements)

    for element in elements:
        generated = set()
        current = identity

        for _ in range(n):
            generated.add(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        if generated == set(elements):
            generators.append(element)

    return generators`,
    testCases: [
      { input: '[0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '[1, 2, 3, 4]', isHidden: false, description: 'Generators of Z5' },
      { input: '[0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '[1, 2]', isHidden: false, description: 'Generators of Z3' },
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '[1, 3]', isHidden: true, description: 'Generators of Z4' }
    ],
    hints: ['Check each element to see if it generates the group', 'An element generates if its cyclic subgroup equals the whole group'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex03',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Generate Cyclic Subgroup',
    difficulty: 2,
    description: 'Generate the cyclic subgroup <g> generated by element g. This is the set {g^n : n in Z}.',
    starterCode: `def cyclic_subgroup(element, elements, operation_table, identity):
    """
    Generate the cyclic subgroup generated by element.

    Args:
        element: The generator element
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of elements in the cyclic subgroup (in order of generation)
    """
    pass`,
    solution: `def cyclic_subgroup(element, elements, operation_table, identity):
    """
    Generate the cyclic subgroup generated by element.

    Args:
        element: The generator element
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of elements in the cyclic subgroup (in order of generation)
    """
    subgroup = []
    current = identity
    n = len(elements)

    for _ in range(n):
        if current in subgroup:
            break
        subgroup.append(current)
        element_index = elements.index(element)
        current_index = elements.index(current)
        current = operation_table[current_index][element_index]

    return subgroup`,
    testCases: [
      { input: '2, [0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '[0, 2, 4, 1, 3]', isHidden: false, description: '<2> in Z5' },
      { input: '2, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '[0, 2]', isHidden: false, description: '<2> in Z4' },
      { input: '1, [0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '[0, 1, 2]', isHidden: true, description: '<1> generates Z3' }
    ],
    hints: ['Start with identity and keep multiplying by the generator', 'Stop when you reach an element you have seen before'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex04',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Check if Group is Cyclic',
    difficulty: 2,
    description: 'Determine if a group is cyclic. A group is cyclic if it has at least one generator.',
    starterCode: `def is_cyclic(elements, operation_table, identity):
    """
    Check if the group is cyclic.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if cyclic, False otherwise
    """
    pass`,
    solution: `def is_cyclic(elements, operation_table, identity):
    """
    Check if the group is cyclic.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if cyclic, False otherwise
    """
    n = len(elements)

    for element in elements:
        generated = set()
        current = identity

        for _ in range(n):
            generated.add(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        if generated == set(elements):
            return True

    return False`,
    testCases: [
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: 'True', isHidden: false, description: 'Z4 is cyclic' },
      { input: '[1, 2, 3, 4], [[1, 2, 3, 4], [2, 1, 4, 3], [3, 4, 1, 2], [4, 3, 2, 1]], 1', expectedOutput: 'False', isHidden: false, description: 'Klein four-group is not cyclic' },
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: 'True', isHidden: true, description: 'Z6 is cyclic' }
    ],
    hints: ['Try each element as a potential generator', 'If any element generates the whole group, it is cyclic'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex05',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Count Generators in Cyclic Group',
    difficulty: 3,
    description: 'For a cyclic group of order n, count the number of generators. This equals φ(n), where φ is Euler\'s totient function.',
    starterCode: `def count_generators(elements, operation_table, identity):
    """
    Count the number of generators in a cyclic group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Number of generators
    """
    pass`,
    solution: `def count_generators(elements, operation_table, identity):
    """
    Count the number of generators in a cyclic group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Number of generators
    """
    count = 0
    n = len(elements)

    for element in elements:
        generated = set()
        current = identity

        for _ in range(n):
            generated.add(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        if generated == set(elements):
            count += 1

    return count`,
    testCases: [
      { input: '[0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '4', isHidden: false, description: 'Z5 has φ(5)=4 generators' },
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '2', isHidden: false, description: 'Z6 has φ(6)=2 generators' },
      { input: '[0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '2', isHidden: true, description: 'Z3 has φ(3)=2 generators' }
    ],
    hints: ['Count elements that generate the entire group', 'For Zn, this equals Euler totient φ(n)'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex06',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find Cyclic Subgroup of Given Order',
    difficulty: 3,
    description: 'Find an element that generates a cyclic subgroup of a specific order, if one exists.',
    starterCode: `def find_subgroup_of_order(n, elements, operation_table, identity):
    """
    Find an element generating a cyclic subgroup of order n.

    Args:
        n: The desired order
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        An element of order n, or None if none exists
    """
    pass`,
    solution: `def find_subgroup_of_order(n, elements, operation_table, identity):
    """
    Find an element generating a cyclic subgroup of order n.

    Args:
        n: The desired order
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        An element of order n, or None if none exists
    """
    for element in elements:
        current = element
        order = 1

        while current != identity:
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]
            order += 1

            if order > len(elements):
                break

        if order == n:
            return element

    return None`,
    testCases: [
      { input: '2, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '2', isHidden: false, description: 'Element of order 2 in Z4' },
      { input: '3, [0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '2', isHidden: false, description: 'Element of order 3 in Z6' },
      { input: '4, [0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: 'None', isHidden: true, description: 'No element of order 4 in Z3' }
    ],
    hints: ['Check the order of each element', 'Return the first element with the desired order'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex07',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'List All Cyclic Subgroups',
    difficulty: 4,
    description: 'Find all distinct cyclic subgroups of a group. Each cyclic subgroup is generated by some element.',
    starterCode: `def all_cyclic_subgroups(elements, operation_table, identity):
    """
    Find all distinct cyclic subgroups.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of cyclic subgroups, each represented as a sorted list
    """
    pass`,
    solution: `def all_cyclic_subgroups(elements, operation_table, identity):
    """
    Find all distinct cyclic subgroups.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        List of cyclic subgroups, each represented as a sorted list
    """
    subgroups = []
    seen = set()
    n = len(elements)

    for element in elements:
        subgroup = []
        current = identity

        for _ in range(n):
            if current in subgroup:
                break
            subgroup.append(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        # Convert to sorted tuple for comparison
        subgroup_tuple = tuple(sorted(subgroup))

        if subgroup_tuple not in seen:
            seen.add(subgroup_tuple)
            subgroups.append(sorted(subgroup))

    return sorted(subgroups)`,
    testCases: [
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '[[0], [0, 2], [0, 1, 2, 3]]', isHidden: false, description: 'Cyclic subgroups of Z4' },
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '[[0], [0, 2, 4], [0, 3], [0, 1, 2, 3, 4, 5]]', isHidden: false, description: 'Cyclic subgroups of Z6' },
      { input: '[0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '[[0], [0, 1, 2]]', isHidden: true, description: 'Cyclic subgroups of Z3' }
    ],
    hints: ['Generate cyclic subgroup for each element', 'Remove duplicates by using sets', 'Sort for consistent output'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex08',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Check Subgroup Generated by Set',
    difficulty: 3,
    description: 'Generate the subgroup generated by a given set of elements. This is the smallest subgroup containing all elements in the set.',
    starterCode: `def subgroup_generated_by(generators, elements, operation_table, identity):
    """
    Find the subgroup generated by the given set of generators.

    Args:
        generators: List of generator elements
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Sorted list of elements in the generated subgroup
    """
    pass`,
    solution: `def subgroup_generated_by(generators, elements, operation_table, identity):
    """
    Find the subgroup generated by the given set of generators.

    Args:
        generators: List of generator elements
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Sorted list of elements in the generated subgroup
    """
    subgroup = {identity}
    changed = True

    while changed:
        changed = False
        new_elements = set()

        for a in subgroup:
            for g in generators:
                a_index = elements.index(a)
                g_index = elements.index(g)
                product = operation_table[a_index][g_index]

                if product not in subgroup:
                    new_elements.add(product)
                    changed = True

        subgroup.update(new_elements)

    return sorted(list(subgroup))`,
    testCases: [
      { input: '[2], [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '[0, 2]', isHidden: false, description: '<2> in Z4' },
      { input: '[1, 2], [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '[0, 1, 2, 3]', isHidden: false, description: '<1,2> generates Z4' },
      { input: '[2, 3], [0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '[0, 1, 2, 3, 4, 5]', isHidden: true, description: '<2,3> generates Z6' }
    ],
    hints: ['Start with identity and generators', 'Keep adding products until no new elements are found', 'This is closure of the generators'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex09',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find Order Using Group Order',
    difficulty: 2,
    description: 'Use Lagrange\'s theorem to determine possible orders of elements. In a group of order n, every element\'s order divides n.',
    starterCode: `def possible_element_orders(group_order):
    """
    Find all possible orders of elements in a group of given order.

    Args:
        group_order: The order of the group

    Returns:
        Sorted list of all divisors of group_order
    """
    pass`,
    solution: `def possible_element_orders(group_order):
    """
    Find all possible orders of elements in a group of given order.

    Args:
        group_order: The order of the group

    Returns:
        Sorted list of all divisors of group_order
    """
    divisors = []

    for i in range(1, group_order + 1):
        if group_order % i == 0:
            divisors.append(i)

    return divisors`,
    testCases: [
      { input: '12', expectedOutput: '[1, 2, 3, 4, 6, 12]', isHidden: false, description: 'Divisors of 12' },
      { input: '7', expectedOutput: '[1, 7]', isHidden: false, description: 'Divisors of prime 7' },
      { input: '8', expectedOutput: '[1, 2, 4, 8]', isHidden: true, description: 'Divisors of 8' }
    ],
    hints: ['Find all divisors of the group order', 'By Lagrange, element orders must divide group order'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex10',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Verify Cyclic Group Property',
    difficulty: 2,
    description: 'Verify that in a cyclic group, every subgroup is also cyclic. Check this for a given cyclic group.',
    starterCode: `def all_subgroups_cyclic(elements, operation_table, identity):
    """
    Check if all subgroups of the group are cyclic.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if all subgroups are cyclic, False otherwise
    """
    pass`,
    solution: `def all_subgroups_cyclic(elements, operation_table, identity):
    """
    Check if all subgroups of the group are cyclic.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        True if all subgroups are cyclic, False otherwise
    """
    # Generate all cyclic subgroups
    cyclic_subgroups = set()
    n = len(elements)

    for element in elements:
        subgroup = []
        current = identity

        for _ in range(n):
            if current in subgroup:
                break
            subgroup.append(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        cyclic_subgroups.add(tuple(sorted(subgroup)))

    # For a cyclic group, the number of subgroups equals the number of divisors
    # and all subgroups are cyclic, so we just check if group is cyclic
    for element in elements:
        generated = set()
        current = identity

        for _ in range(n):
            generated.add(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        if generated == set(elements):
            return True

    return False`,
    testCases: [
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: 'True', isHidden: false, description: 'Z4 is cyclic' },
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: 'True', isHidden: false, description: 'Z6 is cyclic' },
      { input: '[1, 2, 3, 4], [[1, 2, 3, 4], [2, 1, 4, 3], [3, 4, 1, 2], [4, 3, 2, 1]], 1', expectedOutput: 'False', isHidden: true, description: 'Klein group not cyclic' }
    ],
    hints: ['If the group is cyclic, all its subgroups are cyclic', 'Check if the group itself is cyclic'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex11',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find Primitive Root Modulo n',
    difficulty: 3,
    description: 'Find a primitive root modulo n, which is a generator of the multiplicative group (Z/nZ)*.',
    starterCode: `def primitive_root_mod_n(n):
    """
    Find a primitive root modulo n (generator of multiplicative group).

    Args:
        n: The modulus

    Returns:
        A primitive root modulo n, or None if none exists
    """
    pass`,
    solution: `def primitive_root_mod_n(n):
    """
    Find a primitive root modulo n (generator of multiplicative group).

    Args:
        n: The modulus

    Returns:
        A primitive root modulo n, or None if none exists
    """
    def gcd(a, b):
        while b:
            a, b = b, a % b
        return a

    # Find elements coprime to n
    units = [i for i in range(1, n) if gcd(i, n) == 1]

    if not units:
        return None

    phi_n = len(units)

    # Check each unit to see if it generates the group
    for g in units:
        generated = set()
        current = 1

        for _ in range(phi_n):
            generated.add(current)
            current = (current * g) % n

        if len(generated) == phi_n:
            return g

    return None`,
    testCases: [
      { input: '7', expectedOutput: '3', isHidden: false, description: '3 is a primitive root mod 7' },
      { input: '5', expectedOutput: '2', isHidden: false, description: '2 is a primitive root mod 5' },
      { input: '11', expectedOutput: '2', isHidden: true, description: '2 is a primitive root mod 11' }
    ],
    hints: ['Find elements coprime to n', 'Check which element generates all units modulo n', 'Primitive roots exist for n = 1, 2, 4, p^k, 2p^k'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex12',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Count Elements of Each Order',
    difficulty: 3,
    description: 'Create a frequency distribution of element orders in a group.',
    starterCode: `def order_distribution(elements, operation_table, identity):
    """
    Count how many elements have each order.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Dictionary mapping order to count
    """
    pass`,
    solution: `def order_distribution(elements, operation_table, identity):
    """
    Count how many elements have each order.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Dictionary mapping order to count
    """
    distribution = {}

    for element in elements:
        current = element
        order = 1

        while current != identity:
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]
            order += 1

            if order > len(elements):
                break

        if order in distribution:
            distribution[order] += 1
        else:
            distribution[order] = 1

    return distribution`,
    testCases: [
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '{1: 1, 2: 1, 4: 2}', isHidden: false, description: 'Order distribution in Z4' },
      { input: '[0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '{1: 1, 5: 4}', isHidden: false, description: 'Order distribution in Z5' },
      { input: '[0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '{1: 1, 3: 2}', isHidden: true, description: 'Order distribution in Z3' }
    ],
    hints: ['Calculate order of each element', 'Count how many have each order value'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex13',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Express Element as Power of Generator',
    difficulty: 3,
    description: 'Given a cyclic group with generator g, express any element as g^k for some k.',
    starterCode: `def express_as_power(element, generator, elements, operation_table, identity):
    """
    Express element as generator^k.

    Args:
        element: The element to express
        generator: The generator of the cyclic group
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        The exponent k, or None if element not in cyclic group
    """
    pass`,
    solution: `def express_as_power(element, generator, elements, operation_table, identity):
    """
    Express element as generator^k.

    Args:
        element: The element to express
        generator: The generator of the cyclic group
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        The exponent k, or None if element not in cyclic group
    """
    current = identity
    k = 0
    n = len(elements)

    for i in range(n):
        if current == element:
            return k

        generator_index = elements.index(generator)
        current_index = elements.index(current)
        current = operation_table[current_index][generator_index]
        k += 1

    return None`,
    testCases: [
      { input: '3, 1, [0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '3', isHidden: false, description: '3 = 1^3 in Z5' },
      { input: '2, 1, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '2', isHidden: false, description: '2 = 1^2 in Z4' },
      { input: '0, 1, [0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '0', isHidden: true, description: '0 = 1^0 in Z3' }
    ],
    hints: ['Generate powers of generator until you find the element', 'Return the exponent when found'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex14',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find Subgroup Lattice for Cyclic Group',
    difficulty: 4,
    description: 'For a cyclic group, find all subgroups and their containment relationships. In a cyclic group of order n, there is exactly one subgroup of order d for each divisor d of n.',
    starterCode: `def subgroup_lattice(elements, operation_table, identity):
    """
    Find all subgroups and return them organized by size.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Dictionary mapping order to list of subgroups of that order
    """
    pass`,
    solution: `def subgroup_lattice(elements, operation_table, identity):
    """
    Find all subgroups and return them organized by size.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Dictionary mapping order to list of subgroups of that order
    """
    subgroups_by_order = {}
    seen = set()
    n = len(elements)

    for element in elements:
        subgroup = []
        current = identity

        for _ in range(n):
            if current in subgroup:
                break
            subgroup.append(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        subgroup_tuple = tuple(sorted(subgroup))

        if subgroup_tuple not in seen:
            seen.add(subgroup_tuple)
            order = len(subgroup)

            if order not in subgroups_by_order:
                subgroups_by_order[order] = []

            subgroups_by_order[order].append(sorted(subgroup))

    return subgroups_by_order`,
    testCases: [
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '{1: [[0]], 2: [[0, 3]], 3: [[0, 2, 4]], 6: [[0, 1, 2, 3, 4, 5]]}', isHidden: false, description: 'Subgroup lattice of Z6' },
      { input: '[0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '{1: [[0]], 2: [[0, 2]], 4: [[0, 1, 2, 3]]}', isHidden: false, description: 'Subgroup lattice of Z4' },
      { input: '[0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '{1: [[0]], 5: [[0, 1, 2, 3, 4]]}', isHidden: true, description: 'Subgroup lattice of Z5 (prime)' }
    ],
    hints: ['Find all cyclic subgroups', 'Group them by their order', 'For cyclic groups, one subgroup per divisor'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex15',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Verify Generator Order Equals Group Order',
    difficulty: 2,
    description: 'Verify that an element is a generator if and only if its order equals the group order.',
    starterCode: `def generator_iff_order_equals_n(element, elements, operation_table, identity):
    """
    Check if element is a generator and if its order equals group order.

    Args:
        element: The element to check
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Tuple (is_generator, order_equals_n, they_match)
    """
    pass`,
    solution: `def generator_iff_order_equals_n(element, elements, operation_table, identity):
    """
    Check if element is a generator and if its order equals group order.

    Args:
        element: The element to check
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        Tuple (is_generator, order_equals_n, they_match)
    """
    n = len(elements)

    # Check if generator
    generated = set()
    current = identity

    for _ in range(n):
        generated.add(current)
        element_index = elements.index(element)
        current_index = elements.index(current)
        current = operation_table[current_index][element_index]

    is_generator = (generated == set(elements))

    # Find order
    current = element
    order = 1

    while current != identity:
        element_index = elements.index(element)
        current_index = elements.index(current)
        current = operation_table[current_index][element_index]
        order += 1

        if order > n:
            break

    order_equals_n = (order == n)
    they_match = (is_generator == order_equals_n)

    return (is_generator, order_equals_n, they_match)`,
    testCases: [
      { input: '1, [0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '(True, True, True)', isHidden: false, description: '1 is generator with order 5' },
      { input: '2, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '(False, False, True)', isHidden: false, description: '2 has order 2, not generator' },
      { input: '3, [0, 1, 2, 3], [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]], 0', expectedOutput: '(True, True, True)', isHidden: true, description: '3 is generator with order 4' }
    ],
    hints: ['Check if element generates entire group', 'Check if order equals group size', 'These should always match for cyclic groups'],
    language: 'python'
  },
  {
    id: 'math304-t2-ex16',
    subjectId: 'math304',
    topicId: 'math304-topic-2',
    title: 'Find Smallest Generator',
    difficulty: 2,
    description: 'Among all generators of a cyclic group, find the one with smallest numerical value.',
    starterCode: `def smallest_generator(elements, operation_table, identity):
    """
    Find the smallest element that generates the group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        The smallest generator, or None if not cyclic
    """
    pass`,
    solution: `def smallest_generator(elements, operation_table, identity):
    """
    Find the smallest element that generates the group.

    Args:
        elements: List of all elements in the group
        operation_table: 2D list representing the group operation
        identity: The identity element

    Returns:
        The smallest generator, or None if not cyclic
    """
    n = len(elements)
    generators = []

    for element in elements:
        generated = set()
        current = identity

        for _ in range(n):
            generated.add(current)
            element_index = elements.index(element)
            current_index = elements.index(current)
            current = operation_table[current_index][element_index]

        if generated == set(elements):
            generators.append(element)

    if generators:
        return min(generators)
    return None`,
    testCases: [
      { input: '[0, 1, 2, 3, 4], [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]], 0', expectedOutput: '1', isHidden: false, description: 'Smallest generator of Z5 is 1' },
      { input: '[0, 1, 2, 3, 4, 5], [[0, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 0], [2, 3, 4, 5, 0, 1], [3, 4, 5, 0, 1, 2], [4, 5, 0, 1, 2, 3], [5, 0, 1, 2, 3, 4]], 0', expectedOutput: '1', isHidden: false, description: 'Smallest generator of Z6 is 1' },
      { input: '[0, 1, 2], [[0, 1, 2], [1, 2, 0], [2, 0, 1]], 0', expectedOutput: '1', isHidden: true, description: 'Smallest generator of Z3 is 1' }
    ],
    hints: ['Find all generators', 'Return the minimum among them'],
    language: 'python'
  }
];
