import { WrittenExercise } from '../../../../core/types';

export const topic2Exercises: WrittenExercise[] = [
  {
    id: 'math403-t2-ex01',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Basis for Standard Topology on ℝ',
    description: 'Show that the collection of all open intervals (a, b) forms a basis for the standard topology on ℝ.',
    difficulty: 2,
    hints: [
      'Verify both basis axioms',
      'Show that every open set is a union of basis elements',
      'Use the definition of open sets in ℝ'
    ],
    solution: '(B1) For any x ∈ ℝ, we have x ∈ (x-1, x+1), so ⋃ℬ = ℝ. (B2) If x ∈ (a₁, b₁) ∩ (a₂, b₂), let a = max{a₁, a₂} and b = min{b₁, b₂}. Then x ∈ (a, b) ⊆ (a₁, b₁) ∩ (a₂, b₂). Every open set in ℝ is a union of open intervals, so ℬ generates the standard topology.'
  },
  {
    id: 'math403-t2-ex02',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Basis Comparison',
    description: 'Let ℬ₁ and ℬ₂ be bases for topologies τ₁ and τ₂ on X. Prove that τ₁ ⊆ τ₂ if and only if for each x ∈ X and each B₁ ∈ ℬ₁ containing x, there exists B₂ ∈ ℬ₂ such that x ∈ B₂ ⊆ B₁.',
    difficulty: 4,
    hints: [
      'Prove both directions',
      'Use the definition of generated topology',
      'Consider what it means for one topology to be finer than another'
    ],
    solution: '(⇒) Assume τ₁ ⊆ τ₂. Take x ∈ X and B₁ ∈ ℬ₁ with x ∈ B₁. Then B₁ ∈ τ₁ ⊆ τ₂. Since ℬ₂ generates τ₂, we can write B₁ as a union of elements of ℬ₂. In particular, x lies in some B₂ ∈ ℬ₂ with B₂ ⊆ B₁. (⇐) Let U ∈ τ₁. Then U = ⋃ᵢB₁ⁱ where B₁ⁱ ∈ ℬ₁. For each x ∈ B₁ⁱ, there exists B₂ˣ ∈ ℬ₂ with x ∈ B₂ˣ ⊆ B₁ⁱ. Thus U is a union of elements of ℬ₂, so U ∈ τ₂.'
  },
  {
    id: 'math403-t2-ex03',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Subbasis Generation',
    description: 'Let 𝒮 = {(-∞, a), (b, ∞) : a, b ∈ ℝ} be a subbasis for ℝ. Describe the basis generated by 𝒮.',
    difficulty: 2,
    hints: [
      'The basis consists of finite intersections of subbasis elements',
      'Consider intersections of two elements from 𝒮',
      'What types of intervals result?'
    ],
    solution: 'The basis ℬ consists of finite intersections of elements from 𝒮. Intersecting (-∞, a) and (b, ∞): if b < a, we get (b, a); if b ≥ a, we get ∅. Intersecting two sets of the form (-∞, a) gives (-∞, min{a₁, a₂}). Intersecting two sets of the form (b, ∞) gives (max{b₁, b₂}, ∞). Thus ℬ = {∅, ℝ, (a, b), (-∞, a), (b, ∞) : a, b ∈ ℝ}, which generates the standard topology on ℝ.'
  },
  {
    id: 'math403-t2-ex04',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Second Countable Space',
    description: 'Prove that ℝ with the standard topology is second countable.',
    difficulty: 2,
    hints: [
      'Find a countable basis',
      'Consider intervals with rational endpoints',
      'ℚ × ℚ is countable'
    ],
    solution: 'Let ℬ = {(p, q) : p, q ∈ ℚ, p < q}. Since ℚ is countable, ℚ × ℚ is countable, so ℬ is countable. We need to show ℬ is a basis. Take any open set U and x ∈ U. There exists ε > 0 such that (x - ε, x + ε) ⊆ U. Choose rationals p, q with x - ε < p < x < q < x + ε. Then x ∈ (p, q) ⊆ U, so ℬ is a basis. Therefore, ℝ is second countable.'
  },
  {
    id: 'math403-t2-ex05',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Dense Subset Properties',
    description: 'Let A be a dense subset of X. Prove that for every nonempty open set U, we have U ∩ A ≠ ∅.',
    difficulty: 2,
    hints: [
      'Use the definition of dense: cl(A) = X',
      'Suppose U ∩ A = ∅ and derive a contradiction',
      'Consider points in U'
    ],
    solution: 'Since A is dense, cl(A) = X. Take any nonempty open set U and any x ∈ U. Then x ∈ X = cl(A). Since U is a neighborhood of x, and x is in the closure of A, we must have U ∩ A ≠ ∅. Otherwise, U would be a neighborhood of x not meeting A, contradicting x ∈ cl(A).'
  },
  {
    id: 'math403-t2-ex06',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Separable Implies Second Countable',
    description: 'Prove that every separable metric space is second countable.',
    difficulty: 3,
    hints: [
      'Let D be a countable dense subset',
      'Consider balls B(x, 1/n) for x ∈ D and n ∈ ℕ',
      'Show this forms a countable basis'
    ],
    solution: 'Let D be a countable dense subset of the metric space (X, d). Consider ℬ = {B(x, 1/n) : x ∈ D, n ∈ ℕ}. Since D and ℕ are countable, ℬ is countable. To show ℬ is a basis, take any open set U and y ∈ U. There exists ε > 0 with B(y, ε) ⊆ U. Choose n such that 1/n < ε/2. Since D is dense, there exists x ∈ D with d(x, y) < 1/n. Then y ∈ B(x, 1/n) ⊆ B(y, ε) ⊆ U, so ℬ is a basis.'
  },
  {
    id: 'math403-t2-ex07',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Subspace Topology',
    description: 'Let Y ⊆ X and give Y the subspace topology. Prove that a set A ⊆ Y is closed in Y if and only if A = Y ∩ F for some closed set F in X.',
    difficulty: 3,
    hints: [
      'Use the definition of subspace topology',
      'A is closed in Y iff Y \\ A is open in Y',
      'Apply the subspace topology definition to Y \\ A'
    ],
    solution: 'A is closed in Y ⟺ Y \\ A is open in Y ⟺ Y \\ A = Y ∩ U for some open U in X ⟺ A = Y \\ (Y ∩ U) = Y ∩ (X \\ U) where X \\ U is closed in X. Thus A is closed in Y iff A = Y ∩ F for some closed F in X.'
  },
  {
    id: 'math403-t2-ex08',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Basis Existence',
    description: 'Prove that every topology has a basis.',
    difficulty: 2,
    hints: [
      'Consider the topology itself as a collection of sets',
      'Verify the basis axioms',
      'This is almost trivial!'
    ],
    solution: 'Let τ be a topology on X. Then τ itself is a basis for τ. (B1) X ∈ τ, so ⋃τ = X. (B2) If U₁, U₂ ∈ τ and x ∈ U₁ ∩ U₂, then U₁ ∩ U₂ ∈ τ and x ∈ U₁ ∩ U₂ ⊆ U₁ ∩ U₂. Every open set is trivially a union of elements of τ (itself). Thus τ is a basis for itself.'
  },
  {
    id: 'math403-t2-ex09',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Product Basis',
    description: 'Let ℬ₁ and ℬ₂ be bases for topologies on X and Y respectively. Prove that {B₁ × B₂ : B₁ ∈ ℬ₁, B₂ ∈ ℬ₂} is a basis for the product topology on X × Y.',
    difficulty: 3,
    hints: [
      'Verify the two basis axioms',
      'Use properties of bases on X and Y',
      'Consider projections'
    ],
    solution: 'Let ℬ = {B₁ × B₂ : B₁ ∈ ℬ₁, B₂ ∈ ℬ₂}. (B1) Since ℬ₁ and ℬ₂ are bases, ⋃ℬ₁ = X and ⋃ℬ₂ = Y, so ⋃ℬ = X × Y. (B2) Take (x, y) ∈ (B₁ × B₂) ∩ (B₁\' × B₂\'). Then x ∈ B₁ ∩ B₁\' and y ∈ B₂ ∩ B₂\'. Since ℬ₁, ℬ₂ are bases, there exist B₃ ∈ ℬ₁, B₄ ∈ ℬ₂ with x ∈ B₃ ⊆ B₁ ∩ B₁\' and y ∈ B₄ ⊆ B₂ ∩ B₂\'. Then (x, y) ∈ B₃ × B₄ ⊆ (B₁ × B₂) ∩ (B₁\' × B₂\').'
  },
  {
    id: 'math403-t2-ex10',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Lower Limit Topology',
    description: 'The lower limit topology on ℝ has basis ℬ = {[a, b) : a < b}. Show that this topology is strictly finer than the standard topology.',
    difficulty: 3,
    hints: [
      'Show every open interval is open in the lower limit topology',
      'Show some basis element is not open in the standard topology',
      '[0, 1) is not open in the standard topology'
    ],
    solution: 'Every open interval (a, b) can be written as ⋃ₙ [a + 1/n, b), which is open in the lower limit topology. Thus the standard topology is contained in the lower limit topology. However, [0, 1) is open in the lower limit topology but not in the standard topology (0 is not an interior point in the standard topology). Therefore, the lower limit topology is strictly finer than the standard topology.'
  },
  {
    id: 'math403-t2-ex11',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Local Basis',
    description: 'A local basis at x is a collection ℬₓ of neighborhoods of x such that every neighborhood of x contains some element of ℬₓ. Prove that in a metric space, {B(x, 1/n) : n ∈ ℕ} is a local basis at x.',
    difficulty: 2,
    hints: [
      'Take an arbitrary neighborhood U of x',
      'Use the definition of neighborhood in metric spaces',
      'Apply the Archimedean property'
    ],
    solution: 'Let U be a neighborhood of x in the metric space (X, d). Then there exists ε > 0 such that B(x, ε) ⊆ U. By the Archimedean property, there exists n ∈ ℕ such that 1/n < ε. Then B(x, 1/n) ⊆ B(x, ε) ⊆ U. Thus every neighborhood of x contains some B(x, 1/n), making {B(x, 1/n) : n ∈ ℕ} a local basis at x.'
  },
  {
    id: 'math403-t2-ex12',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Relative Topology Basis',
    description: 'Let ℬ be a basis for X and Y ⊆ X. Prove that ℬ_Y = {B ∩ Y : B ∈ ℬ} is a basis for the subspace topology on Y.',
    difficulty: 3,
    hints: [
      'Verify the basis axioms for ℬ_Y',
      'Use the definition of subspace topology',
      'Show every open set in Y is a union of elements from ℬ_Y'
    ],
    solution: '(B1) Since ℬ is a basis for X, we have X = ⋃ℬ, so Y = Y ∩ X = Y ∩ (⋃ℬ) = ⋃{B ∩ Y : B ∈ ℬ}. (B2) Take y ∈ (B₁ ∩ Y) ∩ (B₂ ∩ Y) = (B₁ ∩ B₂) ∩ Y. Since y ∈ B₁ ∩ B₂ and ℬ is a basis, there exists B₃ ∈ ℬ with y ∈ B₃ ⊆ B₁ ∩ B₂. Then y ∈ B₃ ∩ Y ⊆ (B₁ ∩ B₂) ∩ Y. Every open set in Y has the form U ∩ Y where U is a union of elements of ℬ, so it\'s a union of elements of ℬ_Y.'
  },
  {
    id: 'math403-t2-ex13',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Countable Dense Subset',
    description: 'Show that ℝⁿ with the Euclidean topology is separable for all n ∈ ℕ.',
    difficulty: 2,
    hints: [
      'Consider points with rational coordinates',
      'ℚⁿ is countable',
      'Show ℚⁿ is dense in ℝⁿ'
    ],
    solution: 'Let D = ℚⁿ = {(q₁, ..., qₙ) : qᵢ ∈ ℚ}. Since ℚ is countable, ℚⁿ is countable (as a finite product of countable sets). To show D is dense, take any x = (x₁, ..., xₙ) ∈ ℝⁿ and ε > 0. For each i, choose qᵢ ∈ ℚ with |xᵢ - qᵢ| < ε/√n. Then d(x, q) = √(∑(xᵢ - qᵢ)²) < √(n · ε²/n) = ε, where q = (q₁, ..., qₙ) ∈ D. Thus every ball around x contains a point of D, so D is dense. Therefore, ℝⁿ is separable.'
  },
  {
    id: 'math403-t2-ex14',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'First Countable Space',
    description: 'Prove that every metric space is first countable (has a countable local basis at every point).',
    difficulty: 2,
    hints: [
      'For each point x, consider balls of radius 1/n',
      'Show this collection is a local basis at x',
      'Similar to the local basis exercise'
    ],
    solution: 'Let (X, d) be a metric space. For each x ∈ X, let ℬₓ = {B(x, 1/n) : n ∈ ℕ}. Then ℬₓ is countable. We showed in a previous exercise that ℬₓ is a local basis at x: for any neighborhood U of x, there exists ε > 0 with B(x, ε) ⊆ U, and we can find n with 1/n < ε, giving B(x, 1/n) ⊆ U. Since every point has a countable local basis, X is first countable.'
  },
  {
    id: 'math403-t2-ex15',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Nowhere Dense Sets',
    description: 'A set A is nowhere dense if int(cl(A)) = ∅. Show that the Cantor set is nowhere dense in ℝ.',
    difficulty: 3,
    hints: [
      'The Cantor set is closed',
      'Show it has empty interior',
      'The Cantor set contains no intervals'
    ],
    solution: 'The Cantor set C is closed (as an intersection of closed sets), so cl(C) = C. We need to show int(C) = ∅. Suppose int(C) ≠ ∅. Then there exists a nonempty open interval (a, b) ⊆ C. But the Cantor set is constructed by removing open intervals, and every interval contains removed middle thirds. Specifically, the length of C is 0 (sum of removed intervals is 1), so C cannot contain any interval. Thus int(C) = ∅, making C nowhere dense.'
  },
  {
    id: 'math403-t2-ex16',
    subjectId: 'math403',
    topicId: 'math403-topic-2',
    type: 'written',
    title: 'Topology Generated by Metric',
    description: 'Let (X, d) be a metric space. Prove that the collection of all open balls forms a basis for a topology on X.',
    difficulty: 2,
    hints: [
      'Let ℬ = {B(x, r) : x ∈ X, r > 0}',
      'Verify both basis axioms',
      'For (B2), use the triangle inequality'
    ],
    solution: 'Let ℬ = {B(x, r) : x ∈ X, r > 0}. (B1) For any x ∈ X, we have x ∈ B(x, 1), so ⋃ℬ = X. (B2) Let y ∈ B(x₁, r₁) ∩ B(x₂, r₂). Let δ = min{r₁ - d(x₁, y), r₂ - d(x₂, y)}. Then δ > 0. For any z ∈ B(y, δ), we have d(x₁, z) ≤ d(x₁, y) + d(y, z) < d(x₁, y) + δ ≤ r₁, so z ∈ B(x₁, r₁). Similarly, z ∈ B(x₂, r₂). Thus y ∈ B(y, δ) ⊆ B(x₁, r₁) ∩ B(x₂, r₂), so ℬ is a basis.'
  }
];
